[package]
name = "http"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.12.1", optional = true }
chrono = { workspace = true }
domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
actix-web = ["dep:actix-web"]
